<a href="https://colab.research.google.com/github/sahanasubbiah24/churn-prediction/blob/main/notebooks/03_pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
customer_data = {
    "customer_id": [
        "C001",
        "C002",
        "C003",
        "C004",
        "C005",
        "C006",
        "C007",
        "C008"
    ],
    "gender": [
        "Female",
        "Male",
        "Female",
        "Male",
        "Female",
        "Male",
        "Female",
        "Male"
    ],
    "tenure_months": [
        2,
        24,
        13,
        48,
        6,
        36,
        1,
        60
    ],
    "monthly_charge": [
        29.99,
        75.50,
        54.25,
        89.99,
        45.00,
        66.75,
        20.00,
        99.50
    ],
    "contract_type": [
        "Month-to-month",
        "One year",
        "Month-to-month",
        "Two year",
        "Month-to-month",
        "One year",
        "Month-to-month",
        "Two year"
    ],
    "churn": [
        "Yes",
        "No",
        "Yes",
        "No",
        "Yes",
        "No",
        "Yes",
        "No"
    ]
}

customers = pd.DataFrame(customer_data)

customers

  customer_id  gender  tenure_months  monthly_charge   contract_type churn
0        C001  Female              2           29.99  Month-to-month   Yes
1        C002    Male             24           75.50        One year    No
2        C003  Female             13           54.25  Month-to-month   Yes
3        C004    Male             48           89.99        Two year    No
4        C005  Female              6           45.00  Month-to-month   Yes
5        C006    Male             36           66.75        One year    No
6        C007  Female              1           20.00  Month-to-month   Yes
7        C008    Male             60           99.50        Two year    No

In [ ]:
customers.head()

  customer_id  gender  tenure_months  monthly_charge   contract_type churn
0        C001  Female              2           29.99  Month-to-month   Yes
1        C002    Male             24           75.50        One year    No
2        C003  Female             13           54.25  Month-to-month   Yes
3        C004    Male             48           89.99        Two year    No
4        C005  Female              6           45.00  Month-to-month   Yes

In [ ]:
customers.tail()

  customer_id  gender  tenure_months  monthly_charge   contract_type churn
3        C004    Male             48           89.99        Two year    No
4        C005  Female              6           45.00  Month-to-month   Yes
5        C006    Male             36           66.75        One year    No
6        C007  Female              1           20.00  Month-to-month   Yes
7        C008    Male             60           99.50        Two year    No

In [ ]:
customers.shape

(8, 6)

In [ ]:
customers.columns

Index(['customer_id', 'gender', 'tenure_months', 'monthly_charge',
       'contract_type', 'churn'],
      dtype='object')

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     8 non-null      object
 1   gender          8 non-null      object
 2   tenure_months   8 non-null      int64
 3   monthly_charge  8 non-null      float64
 4   contract_type   8 non-null      object
 5   churn           8 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes

In [ ]:
customers.describe()

       tenure_months  monthly_charge
count       8.000000          8.0000
mean       23.750000         60.1225
std        22.275868         28.0408
min         1.000000         20.0000
25%         5.000000         41.2475
50%        18.500000         60.5000
75%        39.000000         79.1225
max        60.000000         99.5000

In [ ]:
customers["monthly_charge"]

0    29.99
1    75.50
2    54.25
3    89.99
4    45.00
5    66.75
6    20.00
7    99.50
Name: monthly_charge, dtype: float64

In [ ]:
customers[
    [
        "customer_id",
        "tenure_months",
        "monthly_charge",
        "churn"
    ]
]

  customer_id  tenure_months  monthly_charge churn
0        C001              2           29.99   Yes
1        C002             24           75.50    No
2        C003             13           54.25   Yes
3        C004             48           89.99    No
4        C005              6           45.00   Yes
5        C006             36           66.75    No
6        C007              1           20.00   Yes
7        C008             60           99.50    No

In [ ]:
high_charge_customers = customers[
    customers["monthly_charge"] > 70
]

high_charge_customers

  customer_id gender  tenure_months  monthly_charge contract_type churn
1        C002   Male             24           75.50      One year    No
3        C004   Male             48           89.99      Two year    No
7        C008   Male             60           99.50      Two year    No

In [ ]:
churned_customers = customers[
    customers["churn"] == "Yes"
]

churned_customers

  customer_id  gender  tenure_months  monthly_charge   contract_type churn
0        C001  Female              2           29.99  Month-to-month   Yes
2        C003  Female             13           54.25  Month-to-month   Yes
4        C005  Female              6           45.00  Month-to-month   Yes
6        C007  Female              1           20.00  Month-to-month   Yes

In [ ]:
new_high_charge_customers = customers[
    (customers["tenure_months"] < 12) &
    (customers["monthly_charge"] > 40)
]

new_high_charge_customers

  customer_id  gender  tenure_months  monthly_charge   contract_type churn
4        C005  Female              6            45.0  Month-to-month   Yes

In [ ]:
customers["estimated_annual_charge"] = (
    customers["monthly_charge"] * 12
)

customers

,customer_id,gender,tenure_months,monthly_charge,contract_type,churn,estimated_annual_charge
0,C001,Female,2,29.99,Month-to-month,Yes,359.88
1,C002,Male,24,75.50,One year,No,906.00
2,C003,Female,13,54.25,Month-to-month,Yes,651.00
3,C004,Male,48,89.99,Two year,No,1079.88
4,C005,Female,6,45.00,Month-to-month,Yes,540.00
5,C006,Male,36,66.75,One year,No,801.00
6,C007,Female,1,20.00,Month-to-month,Yes,240.00
7,C008,Male,60,99.50,Two year,No,1194.00

In [ ]:
customers["estimated_annual_charge"] = (
    customers["estimated_annual_charge"].round(2)
)

customers

,customer_id,gender,tenure_months,monthly_charge,contract_type,churn,estimated_annual_charge
0,C001,Female,2,29.99,Month-to-month,Yes,359.88
1,C002,Male,24,75.50,One year,No,906.00
2,C003,Female,13,54.25,Month-to-month,Yes,651.00
3,C004,Male,48,89.99,Two year,No,1079.88
4,C005,Female,6,45.00,Month-to-month,Yes,540.00
5,C006,Male,36,66.75,One year,No,801.00
6,C007,Female,1,20.00,Month-to-month,Yes,240.00
7,C008,Male,60,99.50,Two year,No,1194.00

In [ ]:
def categorize_tenure(tenure_months):
    if tenure_months < 12:
        return "New"
    elif tenure_months < 36:
        return "Established"
    else:
        return "Long-term"

In [ ]:
customers["tenure_group"] = customers[
    "tenure_months"
].apply(categorize_tenure)

customers

,customer_id,gender,tenure_months,monthly_charge,contract_type,churn,estimated_annual_charge,tenure_group
0,C001,Female,2,29.99,Month-to-month,Yes,359.88,New
1,C002,Male,24,75.50,One year,No,906.00,Established
2,C003,Female,13,54.25,Month-to-month,Yes,651.00,Established
3,C004,Male,48,89.99,Two year,No,1079.88,Long-term
4,C005,Female,6,45.00,Month-to-month,Yes,540.00,New
5,C006,Male,36,66.75,One year,No,801.00,Long-term
6,C007,Female,1,20.00,Month-to-month,Yes,240.00,New
7,C008,Male,60,99.50,Two year,No,1194.00,Long-term

In [ ]:
customers["churn_numeric"] = customers[
    "churn"
].map({
    "No": 0,
    "Yes": 1
})

customers

,customer_id,gender,tenure_months,monthly_charge,contract_type,churn,estimated_annual_charge,tenure_group,churn_numeric
0,C001,Female,2,29.99,Month-to-month,Yes,359.88,New,1
1,C002,Male,24,75.50,One year,No,906.00,Established,0
2,C003,Female,13,54.25,Month-to-month,Yes,651.00,Established,1
3,C004,Male,48,89.99,Two year,No,1079.88,Long-term,0
4,C005,Female,6,45.00,Month-to-month,Yes,540.00,New,1
5,C006,Male,36,66.75,One year,No,801.00,Long-term,0
6,C007,Female,1,20.00,Month-to-month,Yes,240.00,New,1
7,C008,Male,60,99.50,Two year,No,1194.00,Long-term,0

In [ ]:
customers_sorted = customers.sort_values(
    by="monthly_charge",
    ascending=False
)

customers_sorted

,customer_id,gender,tenure_months,monthly_charge,contract_type,churn,estimated_annual_charge,tenure_group,churn_numeric
7,C008,Male,60,99.50,Two year,No,1194.00,Long-term,0
3,C004,Male,48,89.99,Two year,No,1079.88,Long-term,0
1,C002,Male,24,75.50,One year,No,906.00,Established,0
5,C006,Male,36,66.75,One year,No,801.00,Long-term,0
2,C003,Female,13,54.25,Month-to-month,Yes,651.00,Established,1
4,C005,Female,6,45.00,Month-to-month,Yes,540.00,New,1
0,C001,Female,2,29.99,Month-to-month,Yes,359.88,New,1
6,C007,Female,1,20.00,Month-to-month,Yes,240.00,New,1

In [ ]:
customers.sort_values(
    by=["contract_type", "tenure_months"],
    ascending=[True, False]
)

,customer_id,gender,tenure_months,monthly_charge,contract_type,churn,estimated_annual_charge,tenure_group,churn_numeric
2,C003,Female,13,54.25,Month-to-month,Yes,651.00,Established,1
4,C005,Female,6,45.00,Month-to-month,Yes,540.00,New,1
0,C001,Female,2,29.99,Month-to-month,Yes,359.88,New,1
6,C007,Female,1,20.00,Month-to-month,Yes,240.00,New,1
5,C006,Male,36,66.75,One year,No,801.00,Long-term,0
1,C002,Male,24,75.50,One year,No,906.00,Established,0
7,C008,Male,60,99.50,Two year,No,1194.00,Long-term,0
3,C004,Male,48,89.99,Two year,No,1079.88,Long-term,0

In [ ]:
average_charge_by_churn = customers.groupby(
    "churn"
)["monthly_charge"].mean()

average_charge_by_churn

churn
No     82.935
Yes    37.310
Name: monthly_charge, dtype: float64

In [ ]:
contract_summary = customers.groupby(
    "contract_type"
).agg(
    customer_count=("customer_id", "count"),
    average_tenure=("tenure_months", "mean"),
    average_monthly_charge=("monthly_charge", "mean"),
    churn_rate=("churn_numeric", "mean")
)

contract_summary

,customer_count,average_tenure,average_monthly_charge,churn_rate
contract_type,,,,
Month-to-month,4,5.5,37.310,1.0
One year,2,30.0,71.125,0.0
Two year,2,54.0,94.745,0.0

In [ ]:
contract_summary["churn_rate_percent"] = (
    contract_summary["churn_rate"] * 100
).round(1)

contract_summary

,customer_count,average_tenure,average_monthly_charge,churn_rate,churn_rate_percent
contract_type,,,,,
Month-to-month,4,5.5,37.310,1.0,100.0
One year,2,30.0,71.125,0.0,0.0
Two year,2,54.0,94.745,0.0,0.0

In [ ]:
service_data = {
    "customer_id": [
        "C001",
        "C002",
        "C003",
        "C004",
        "C005",
        "C006",
        "C007",
        "C008"
    ],
    "internet_service": [
        "DSL",
        "Fiber optic",
        "DSL",
        "Fiber optic",
        "DSL",
        "Fiber optic",
        "No",
        "Fiber optic"
    ],
    "support_plan": [
        "No",
        "Yes",
        "No",
        "Yes",
        "No",
        "Yes",
        "No",
        "Yes"
    ]
}

services = pd.DataFrame(service_data)

services

  customer_id internet_service support_plan
0        C001              DSL           No
1        C002      Fiber optic          Yes
2        C003              DSL           No
3        C004      Fiber optic          Yes
4        C005              DSL           No
5        C006      Fiber optic          Yes
6        C007               No           No
7        C008      Fiber optic          Yes

In [ ]:
customer_services = customers.merge(
    services,
    on="customer_id",
    how="left"
)

customer_services

,customer_id,gender,tenure_months,monthly_charge,contract_type,churn,estimated_annual_charge,tenure_group,churn_numeric,internet_service,support_plan
0,C001,Female,2,29.99,Month-to-month,Yes,359.88,New,1,DSL,No
1,C002,Male,24,75.50,One year,No,906.00,Established,0,Fiber optic,Yes
2,C003,Female,13,54.25,Month-to-month,Yes,651.00,Established,1,DSL,No
3,C004,Male,48,89.99,Two year,No,1079.88,Long-term,0,Fiber optic,Yes
4,C005,Female,6,45.00,Month-to-month,Yes,540.00,New,1,DSL,No
5,C006,Male,36,66.75,One year,No,801.00,Long-term,0,Fiber optic,Yes
6,C007,Female,1,20.00,Month-to-month,Yes,240.00,New,1,No,No
7,C008,Male,60,99.50,Two year,No,1194.00,Long-term,0,Fiber optic,Yes

In [ ]:
customer_services.to_csv(
    "customer_practice_data.csv",
    index=False
)

In [ ]:
from google.colab import files

files.download("customer_practice_data.csv")